### PR TITLE
various package status improvement

### PR DESCRIPTION
**Pull request by johnnychen94**
Instead of doing https://github.com/JuliaImages/ImageFiltering.jl/pull/235 I think it might be worth improving this package first 😆 

This PR doesn't touch the core functionality with one exception `rayleighmode` reworked using ImageContrastAdjustment.

Depending on how you want this package to work closely with the JuliaImages ecosystem, I can contribute more to e.g., improve test codes, docstrings, and potentially improve the core implementation when I'm confident.

### CODE REVIEW

**Comment by peterkovesi** [comment]
Thank you for all the work you have done.  Getting the dependencies down is a good thing.  However, it looks like AbstractFFTs needs to be reinstated (or it is being unnecessarily used somewhere)
I was not familiar with your DemoCards package, looks neat.

You are most welcome to make improvements to this package as you wish.  I am delighted that you are interested in the package.  On my own all I would be doing is trying to keep compat entries maintained and otherwise doing the bare minimum to keep the package useable.

**Comment by johnnychen94** [comment]
> However, it looks like AbstractFFTs needs to be reinstated (or it is being unnecessarily used somewhere)

Right, I missed committing one change. It seems that this repo has messed up with whitespace issues. VSCode makes a bunch of auto-fixes and it makes tracking changes quite hard :joy: 

<details>
<summary> screenshot </summary>

image

</details>

Can you run some whitespace fixes on the git history?  For instance, the `ws-fix.sh` in https://stackoverflow.com/questions/18076263/remove-historical-trailing-white-spaces-in-git works quite well. I also made a cleaned version in https://github.com/johnnychen94/ImagePhaseCongruency.jl/tree/master-ws-fix

---

DemoCards is used to support all these kinds of examples and tutorials. It follows a mixed syntax of Documenter and [Literate.jl](https://github.com/fredrikekre/Literate.jl). Currently, we need to wait for Images v0.25 out first. But if you're interested to check it locally, you can try to add https://github.com/JuliaImages/Images.jl/pull/971 branch.

---

I'm definitely interested in improving the status of this package; you're really an expert on this and I think people should be grateful to use them. I'm also considering making this package an external extension to ImageFiltering, or forking the functionality into ImageFiltering. I'm not sure yet which is better, but I do want to advertise your packages in JuliaImages. Or if you want to make them exposed more, you're welcome to transfer your packages to JuliaImages.

**Comment by johnnychen94** [comment]
Thanks for the invitation!

**Comment by peterkovesi** [comment]
I am not sure about the whitespace fixing.  All I know is the basics of git - just enough to get me into trouble!
I have invited you to be a collaborator.  If it is OK with you you can perform the whitespace fixing.
Sorry not to be participating much at the moment I am busy with other things - I am about to head off on a long sailing trip!

**Comment by johnnychen94** [comment]
Enjoy the trip and your retired life 😆

**Comment by johnnychen94** [comment]
> If it is OK with you you can perform the whitespace fixing.

Done. You'll have to do a force-reset on your local repo to get the updated history:

```bash
git fetch --all
git checkout master
git reset --hard origin/master
```

**Pull request merged**
